#!/usr/bin/env python3
"""
A2A Generator Script

This script generates A2A server files and agent cards for any ADK agent.

Usage:
    python a2a_generator.py <agent_folder> [--port PORT] [--name NAME]

Examples:
    python a2a_generator.py ./MyAgent --port 10010 --name "My Custom Agent"
    python a2a_generator.py /path/to/agent
"""

import argparse
import json
import os
import sys
from pathlib import Path


def generate_agent_card(
    agent_name: str,
    description: str,
    port: int,
    skills: list = None,
    version: str = "1.0.0"
) -> dict:
    """Generate an agent card JSON structure."""
    
    if skills is None:
        skills = [
            {
                "id": "default_skill",
                "name": f"{agent_name} Default Skill",
                "description": f"Default capability of {agent_name}",
                "tags": ["agent"],
                "examples": [f"Use {agent_name} to help me"]
            }
        ]
    
    return {
        "name": agent_name,
        "description": description,
        "version": version,
        "protocolVersion": "0.2.1",
        "url": f"http://localhost:{port}/a2a",
        "capabilities": {
            "streaming": True,
            "pushNotifications": False,
            "stateTransitionHistory": True
        },
        "skills": skills,
        "defaultInputModes": ["text"],
        "defaultOutputModes": ["text"],
        "provider": {
            "organization": "Capstone Project",
            "url": "https://github.com/capstone"
        }
    }


def generate_a2a_server(agent_name: str, port: int) -> str:
    """Generate A2A server Python code."""
    
    return f'''"""
A2A Server for {agent_name}

This module exposes the {agent_name} via the A2A (Agent-to-Agent) protocol,
allowing other agents to communicate with it over HTTP.

Auto-generated by a2a_generator.py
"""

import os
import sys
from pathlib import Path

# Add parent directories to path
sys.path.insert(0, str(Path(__file__).parent))
sys.path.insert(0, str(Path(__file__).parent.parent))

# Load environment variables
from dotenv import load_dotenv
capstone_root = Path(__file__).resolve()
# Try to find .env going up the directory tree
for i in range(5):
    capstone_root = capstone_root.parent
    env_path = capstone_root / '.env'
    if env_path.exists():
        load_dotenv(dotenv_path=env_path)
        break

# Set service account path if exists
service_account_path = capstone_root / 'service_account.json'
if service_account_path.exists():
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = str(service_account_path.absolute())

# Import the agent
from agent import root_agent

# Import A2A utilities
try:
    from google.adk.a2a.utils.agent_to_a2a import to_a2a
except ImportError:
    print("Error: google.adk.a2a not available. Please update google-adk package.")
    print("Run: pip install --upgrade google-adk")
    sys.exit(1)

# Port configuration
A2A_PORT = int(os.environ.get("{agent_name.upper().replace(" ", "_")}_A2A_PORT", "{port}"))

# Create the A2A application
print(f"🚀 Starting {agent_name} A2A Server on port {{A2A_PORT}}")
a2a_app = to_a2a(root_agent, port=A2A_PORT)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(a2a_app, host="0.0.0.0", port=A2A_PORT)
'''


def add_a2a_to_agent(
    agent_folder: Path,
    agent_name: str = None,
    description: str = None,
    port: int = 10000,
    force: bool = False
):
    """Add A2A support to an agent folder."""
    
    agent_folder = Path(agent_folder).resolve()
    
    if not agent_folder.exists():
        raise FileNotFoundError(f"Agent folder not found: {agent_folder}")
    
    agent_py = agent_folder / "agent.py"
    if not agent_py.exists():
        raise FileNotFoundError(f"agent.py not found in {agent_folder}")
    
    # Auto-detect agent name from folder
    if not agent_name:
        agent_name = agent_folder.name
    
    # Auto-detect description from agent.py
    if not description:
        with open(agent_py, 'r') as f:
            content = f.read()
            # Try to extract description from agent definition
            if 'description=' in content:
                import re
                match = re.search(r'description\s*=\s*["\']([^"\']+)["\']', content)
                if match:
                    description = match.group(1)
        if not description:
            description = f"{agent_name} - A Google ADK Agent"
    
    # Check for existing files
    a2a_server_path = agent_folder / "a2a_server.py"
    agent_card_path = agent_folder / "agent_card.json"
    
    if not force:
        if a2a_server_path.exists():
            print(f"⚠️  a2a_server.py already exists in {agent_folder}. Use --force to overwrite.")
            return
        if agent_card_path.exists():
            print(f"⚠️  agent_card.json already exists in {agent_folder}. Use --force to overwrite.")
            return
    
    # Generate files
    print(f"\n📦 Adding A2A support to {agent_name}")
    print(f"   Folder: {agent_folder}")
    print(f"   Port: {port}")
    
    # Generate and write agent card
    agent_card = generate_agent_card(agent_name, description, port)
    with open(agent_card_path, 'w') as f:
        json.dump(agent_card, f, indent=2)
    print(f"   ✅ Created: agent_card.json")
    
    # Generate and write a2a_server.py
    a2a_server = generate_a2a_server(agent_name, port)
    with open(a2a_server_path, 'w') as f:
        f.write(a2a_server)
    print(f"   ✅ Created: a2a_server.py")
    
    # Check for __init__.py and create if needed
    init_path = agent_folder / "__init__.py"
    if not init_path.exists():
        with open(init_path, 'w') as f:
            f.write(f'''from .agent import root_agent

__all__ = ["root_agent"]
''')
        print(f"   ✅ Created: __init__.py")
    
    print(f"\n🎉 A2A support added to {agent_name}!")
    print(f"\nTo start the A2A server:")
    print(f"  cd {agent_folder}")
    print(f"  python a2a_server.py")
    print(f"\nAgent card URL: http://localhost:{port}/a2a/{agent_name}/.well-known/agent.json")


def main():
    parser = argparse.ArgumentParser(
        description="Add A2A support to an ADK agent",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s ./MyAgent --port 10010
  %(prog)s ./MyAgent --name "My Agent" --description "A helpful agent"
  %(prog)s ./agents/HelperAgent --force
        """
    )
    
    parser.add_argument("agent_folder", help="Path to the agent folder containing agent.py")
    parser.add_argument("--port", "-p", type=int, default=10000, help="A2A server port (default: 10000)")
    parser.add_argument("--name", "-n", help="Agent name (default: folder name)")
    parser.add_argument("--description", "-d", help="Agent description")
    parser.add_argument("--force", "-f", action="store_true", help="Overwrite existing files")
    
    args = parser.parse_args()
    
    try:
        add_a2a_to_agent(
            args.agent_folder,
            agent_name=args.name,
            description=args.description,
            port=args.port,
            force=args.force
        )
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()

